### ISSUE TITLE
Unicode identifiers are not supported in SQLite

### ISSUE THREAD

**Issue by kemisstep** [nene/sql-parser-cst#45]
中文字段不支持，需要加 ``

**Comment by kemisstep** [comment]
like this will error 

Syntax Error: Unexpected 

![image](https://github.com/nene/sql-parser-cst/assets/117804089/7b7db578-c1f7-4d2d-9147-bb553aeb1d6e)

**Comment by nene** [comment]
Thanks for the clarification.

It seems that SQLite indeed supports unicode identifiers. Unfortunately SQLite documentation doesn't seem to contain any information about the syntax of supported identifiers.

Should be simple to fix though as I've already implemented unicode identifier support for MySQL, MariaDB and PostgreSQL.
