### ISSUE TITLE
Postgres support (DML)

### ISSUE THREAD

**Issue by nene** [nene/sql-parser-cst#47]
#### DML

- [x] [INSERT INTO](https://www.postgresql.org/docs/current/sql-insert.html)
    - [x] WITH clause
    - [x] `AS alias`
    - [x] `OVERRIDING { SYSTEM | USER } VALUE`
    - [x] `DEFAULT VALUES`
    - [x] `DEFAULT` in values list
    - [x] insert a query
    - [x] `ON CONFLICT` clause
        - [x] `ON CONFLICT (col1, col2, ...)`
        - [x] `ON CONFLICT ((expr1), (expr2))`
        - [x] `ON CONFLICT (func1(), func2())`
        - [x] `ON CONFLICT (col1 {ASC | DESC})`
        - [x] `ON CONFLICT (col1 NULLS {FIRST | LAST})`
        - [x] `ON CONFLICT (col1 COLLATE myCollation)`
        - [x] `ON CONFLICT (col1 opclass)` where opclass is an identifier like `int4_ops`
        - [x] `ON CONFLICT (col1) WHERE index_predicate`
        - [x] `ON CONFLICT ON CONSTRAINT name`
        - [x] `... DO NOTHING`
        - [x] `... UPDATE SET col1 = expr, col2 = DEFAULT`
        - [x] `... UPDATE SET (col1, col2) = (expr, DEFAULT)`
        - [x] `... UPDATE SET (col1, col2) = ROW (expr, DEFAULT)`
        - [x] `... UPDATE SET ... WHERE condition`
    - [x] `RETURNING col1, col2, ...`
    - [x] `RETURNING *`
    - [x] `RETURNING output_expression [[AS] output_name]`
- [x] [UPDATE](https://www.postgresql.org/docs/current/sql-update.html)
    - [x] WITH clause
    - [x] `UPDATE [ONLY] tablename`
    - [x] `tablename *`
    - [x] `[AS] alias`
    - [x] `SET col = DEFAULT`
    - [x] multi-column assignment: `(col1, col2) = (1, 2)`
    - [x] `SET (col1, col2) = ROW (expr1, expr2)`
    - [x] `SET (col1, col2) = ROW (DEFAULT, ...)`
    - [x] sub-select assignment:`col = (SELECT ...)`
    - [x] `FROM`
    - [x] `WHERE`
    - [x] `WHERE CURRENT OF cursor`
    - [x] `RETURNING *`
    - [x] `RETURNING output_expression [[AS] output_name]`
- [x] [DELETE FROM](https://www.postgresql.org/docs/current/sql-delete.html)
    - [x] WITH clause
    - [x] `ONLY`
    - [x] `tablename *`
    - [x] `[AS] alias`
    - [x] `USING from_item, ...`
    - [x] `WHERE`
    - [x] `WHERE CURRENT OF cursor`
    - [x] `RETURNING *`
    - [x] `RETURNING output_expression [[AS] output_name]`
- [x] [MERGE INTO](https://www.postgresql.org/docs/current/sql-merge.html)
    - [x] WITH clause
    - [x] `MERGE INTO [ONLY]`
    - [x] `tablename *`
    - [x] `AS alias`
    - [x] `USING [ONLY] tablename [*] ON join_condition`
    - [x] `USING (query) [[AS] alias] ON join_condition`
    - [x] `WHEN [NOT] MATCHED [AND condition] THEN action`
    - [x] merge actions:
        - [x] `DO NOTHING`
        - [x] `DELETE`
        - [x] `UPDATE SET ...`
        - [x] `INSERT [( column_name [, ...] )] VALUES ( ... )`
        - [x] `INSERT ... DEFAULT VALUES`
        - [x] `INSERT OVERRIDING { SYSTEM | USER } VALUE ...`
- [x] [TRUNCATE](https://www.postgresql.org/docs/current/sql-truncate.html)
    - [x] `TRUNCATE [TABLE]`
    - [x] `TRUNCATE [ONLY]`
    - [x] multi-table truncate
    - [x] `tablename *`
    - [x] `RESTART IDENTITY | CONTINUE IDENTITY`
    - [x] `CASCADE | RESTRICT`

**Comment by jming422** [comment]
Hi again, I found a bit here that isn't working as expected -- I know PostgreSQL is still experimental, so hopefully this info helps with the implementation effort!

I've found that INSERT statement CTEs don't work if the CTE is another INSERT, e.g.

```javascript
// works
const q = psql`
  WITH stuff AS (SELECT foo FROM bar)
  INSERT INTO thing
  SELECT foo FROM stuff;
`;

// works
const q2 = psql`INSERT INTO bar (foo) SELECT '...' FROM somewhere RETURNING id;`;

// doesn't work
const q3 = psql`
  WITH stuff AS (INSERT INTO bar (foo) SELECT '...' FROM somewhere RETURNING id)
  INSERT INTO thing
  SELECT id FROM stuff;
`;

```

The error message looks like this:
```
❯ npx prettier --check --config .prettierrc.yml "js-packages/myproject-backend/**/*.{js,json,yml,md}"
Checking formatting...
js-packages/myproject-backend/src/test.jsFormattedSyntaxError: Syntax Error: Unexpected ")"
Was expecting to see: "!=", "%", "&", "'", "(", "*", "+", ",", "-", "->", "->>", ".", "/", "<", "<<", "<=", "<=>", "<>", "=", "==", ">", ">=", ">>", "AND", "AS", "BETWEEN", "COLLATE", "DIV", "GLOB", "IN", "IS", "ISNULL", "LIKE", "MATCH", "MOD", "NOT", "NOTNULL", "OR", "REGEXP", "RLIKE", "|", "||", identifier, or whitespace
--> /Users/jming/Documents/myproject/js-packages/myproject-backend/src/test.js:1:78
  |
1 | WITH stuff AS (INSERT INTO bar (foo) SELECT '...' FROM somewhere RETURNING id)
  |                                                                              ^
    at parse (/Users/jming/Documents/myproject/node_modules/sql-parser-cst/lib/main.js:40:19)
    at Object.parse (/Users/jming/Documents/myproject/node_modules/prettier-plugin-sql-cst/dist/index.js:41:76)
    at parse4 (file:///Users/jming/Documents/myproject/node_modules/prettier/index.mjs:22117:24)
    at async textToDoc (file:///Users/jming/Documents/myproject/node_modules/prettier/index.mjs:22224:19)
    at async jr (file:///Users/jming/Documents/myproject/node_modules/prettier-plugin-embed/dist/index.js:1402:15)
    at async file:///Users/jming/Documents/myproject/node_modules/prettier-plugin-embed/dist/index.js:2356:17
    at async printEmbeddedLanguages (file:///Users/jming/Documents/myproject/node_modules/prettier/index.mjs:22168:20)
    at async printAstToDoc (file:///Users/jming/Documents/myproject/node_modules/prettier/index.mjs:22257:3)
    at async coreFormat (file:///Users/jming/Documents/myproject/node_modules/prettier/index.mjs:22611:14)
    at async formatWithCursor (file:///Users/jming/Documents/myproject/node_modules/prettier/index.mjs:22809:14)
All matched files use Prettier code style!

```

**Comment by nene** [comment]
Thanks for reporting.

Should be a simple thing to fix. Simply the result of DML statements not
being supported in CTE-s by other SQL dialects covered by this parser.

**Comment by nene** [comment]
@jming422, so I came back to fix this problem again and discovered that it's in fact all working just as expected.

It appears that you have simply not configured the prettier plugin to use the "postgresql" parser, instead likely using the default "sqlite" parser, which doesn't support this syntax.

**Comment by jming422** [comment]
Ah, you're right, apologies for the misguided bug report! I'm also trying to configure `prettier-plugin-embed` using [this option](https://github.com/Sec-ant/prettier-plugin-embed?tab=readme-ov-file#embeddedoverrides-1) which isn't behaving like I expected. Thanks for pointing me in the right direction
