### ISSUE TITLE
Postgres support

### ISSUE THREAD

**Issue by kevbook** [nene/sql-parser-cst#71]
Just adding, so you can dig into this. Following fails:

```sql
/** -------------------------------------------------------
 * Reset the current session role to the original session
 * ------------------------------------------------------- */
SET ROLE NONE;
```

```sql
SELECT *,
  rolconfig AS search_path,
  ARRAY(SELECT t3.rolname
    FROM pg_catalog.pg_auth_members t2
    JOIN pg_catalog.pg_roles t3 ON (t2.roleid = t3.oid)
    WHERE t1.oid = t2.member) as member_of
FROM pg_catalog.pg_roles t1
WHERE t1.rolname !~ '^(pg_|rds|neon_|cloud_|supabase_|_aiven)'
ORDER BY rolname;
```

**Comment by nene** [comment]
- the first part is obvious. The `SET` statement is not yet supported (like many other postgres-specific statements).
- the second part is more interesting. It doesn't expect the keyword `ARRAY` to be also used as a function name. Should be a fairly simple fix.

**Comment by nene** [comment]
- Fixed the array() syntax support.
- Created a separate issue for users/roles/groups syntax support: #73
