### ISSUE TITLE
Great job

### ISSUE THREAD

**Issue by grant-d** [nene/sql-parser-cst#8]
@nene , great job on this lib. We are using a similar lib that I created using `antlr`. While it works fine, it is heavy and the antlr DSL and build steps make it onerous to maintain. I had been looking at using `pegjs` instead, but hadn't got around to doing so. 

Looks like you have built a comprehensive parser, thanks again

A couple of questions:
- Are you planning on adding it to `npm` any time soon. Else we will just fork and include directly
- We have specific smarts around [json](https://www.sqlite.org/json1.html) in `sqlite`. Are you planning on any work here. If not no problem.

**Comment by grant-d** [comment]
Oh. Just noticed you are `GPL`. OK, no problem. We will keep using `antlr`, we have an `MIT` requirement.
Still, great job.

**Comment by nene** [comment]
Thanks for the feedback. Nice to hear you like it. Sad to hear that you can't use it :(

As a response to your questions:

- It is already on npm.
- No plan to do anything with JSON literals in SQL.
